/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ApiCallbackRouteImport } from './routes/api/callback'
import { Route as ApiCheckIpRouteImport } from './routes/api/check-ip'
import { Route as ApiFlagRouteImport } from './routes/api/flag'
import { Route as ApiAuditGuildIdRouteImport } from './routes/api/audit.$guildId'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth.callback'
import { Route as ApiAuthDiscordRouteImport } from './routes/api/auth.discord'
import { Route as ApiGuildGuildIdRouteImport } from './routes/api/guild.$guildId'
import { Route as ApiGuildRegisterRouteImport } from './routes/api/guild.register'
import { Route as ApiGuildTokenRouteImport } from './routes/api/guild.token'
import { Route as ApiSuspiciousGuildIdRouteImport } from './routes/api/suspicious.$guildId'
import { Route as ApiVerifyTokenRouteImport } from './routes/api/verify.$token'
import { Route as ApiVerifyPendingRouteImport } from './routes/api/verify.pending'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallbackRoute = ApiCallbackRouteImport.update({
  id: '/api/callback',
  path: '/api/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckIpRoute = ApiCheckIpRouteImport.update({
  id: '/api/check-ip',
  path: '/api/check-ip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlagRoute = ApiFlagRouteImport.update({
  id: '/api/flag',
  path: '/api/flag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditGuildIdRoute = ApiAuditGuildIdRouteImport.update({
  id: '/api/audit/$guildId',
  path: '/api/audit/$guildId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordRoute = ApiAuthDiscordRouteImport.update({
  id: '/api/auth/discord',
  path: '/api/auth/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuildGuildIdRoute = ApiGuildGuildIdRouteImport.update({
  id: '/api/guild/$guildId',
  path: '/api/guild/$guildId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuildRegisterRoute = ApiGuildRegisterRouteImport.update({
  id: '/api/guild/register',
  path: '/api/guild/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuildTokenRoute = ApiGuildTokenRouteImport.update({
  id: '/api/guild/token',
  path: '/api/guild/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuspiciousGuildIdRoute = ApiSuspiciousGuildIdRouteImport.update({
  id: '/api/suspicious/$guildId',
  path: '/api/suspicious/$guildId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyTokenRoute = ApiVerifyTokenRouteImport.update({
  id: '/api/verify/$token',
  path: '/api/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyPendingRoute = ApiVerifyPendingRouteImport.update({
  id: '/api/verify/pending',
  path: '/api/verify/pending',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/verify': typeof VerifyRoute
  '/api/callback': typeof ApiCallbackRoute
  '/api/check-ip': typeof ApiCheckIpRoute
  '/api/flag': typeof ApiFlagRoute
  '/api/audit/$guildId': typeof ApiAuditGuildIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/discord': typeof ApiAuthDiscordRoute
  '/api/guild/$guildId': typeof ApiGuildGuildIdRoute
  '/api/guild/register': typeof ApiGuildRegisterRoute
  '/api/guild/token': typeof ApiGuildTokenRoute
  '/api/suspicious/$guildId': typeof ApiSuspiciousGuildIdRoute
  '/api/verify/$token': typeof ApiVerifyTokenRoute
  '/api/verify/pending': typeof ApiVerifyPendingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verify': typeof VerifyRoute
  '/api/callback': typeof ApiCallbackRoute
  '/api/check-ip': typeof ApiCheckIpRoute
  '/api/flag': typeof ApiFlagRoute
  '/api/audit/$guildId': typeof ApiAuditGuildIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/discord': typeof ApiAuthDiscordRoute
  '/api/guild/$guildId': typeof ApiGuildGuildIdRoute
  '/api/guild/register': typeof ApiGuildRegisterRoute
  '/api/guild/token': typeof ApiGuildTokenRoute
  '/api/suspicious/$guildId': typeof ApiSuspiciousGuildIdRoute
  '/api/verify/$token': typeof ApiVerifyTokenRoute
  '/api/verify/pending': typeof ApiVerifyPendingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/verify': typeof VerifyRoute
  '/api/callback': typeof ApiCallbackRoute
  '/api/check-ip': typeof ApiCheckIpRoute
  '/api/flag': typeof ApiFlagRoute
  '/api/audit/$guildId': typeof ApiAuditGuildIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/discord': typeof ApiAuthDiscordRoute
  '/api/guild/$guildId': typeof ApiGuildGuildIdRoute
  '/api/guild/register': typeof ApiGuildRegisterRoute
  '/api/guild/token': typeof ApiGuildTokenRoute
  '/api/suspicious/$guildId': typeof ApiSuspiciousGuildIdRoute
  '/api/verify/$token': typeof ApiVerifyTokenRoute
  '/api/verify/pending': typeof ApiVerifyPendingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/verify'
    | '/api/callback'
    | '/api/check-ip'
    | '/api/flag'
    | '/api/audit/$guildId'
    | '/api/auth/callback'
    | '/api/auth/discord'
    | '/api/guild/$guildId'
    | '/api/guild/register'
    | '/api/guild/token'
    | '/api/suspicious/$guildId'
    | '/api/verify/$token'
    | '/api/verify/pending'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/verify'
    | '/api/callback'
    | '/api/check-ip'
    | '/api/flag'
    | '/api/audit/$guildId'
    | '/api/auth/callback'
    | '/api/auth/discord'
    | '/api/guild/$guildId'
    | '/api/guild/register'
    | '/api/guild/token'
    | '/api/suspicious/$guildId'
    | '/api/verify/$token'
    | '/api/verify/pending'
  id:
    | '__root__'
    | '/'
    | '/verify'
    | '/api/callback'
    | '/api/check-ip'
    | '/api/flag'
    | '/api/audit/$guildId'
    | '/api/auth/callback'
    | '/api/auth/discord'
    | '/api/guild/$guildId'
    | '/api/guild/register'
    | '/api/guild/token'
    | '/api/suspicious/$guildId'
    | '/api/verify/$token'
    | '/api/verify/pending'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VerifyRoute: typeof VerifyRoute
  ApiCallbackRoute: typeof ApiCallbackRoute
  ApiCheckIpRoute: typeof ApiCheckIpRoute
  ApiFlagRoute: typeof ApiFlagRoute
  ApiAuditGuildIdRoute: typeof ApiAuditGuildIdRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthDiscordRoute: typeof ApiAuthDiscordRoute
  ApiGuildGuildIdRoute: typeof ApiGuildGuildIdRoute
  ApiGuildRegisterRoute: typeof ApiGuildRegisterRoute
  ApiGuildTokenRoute: typeof ApiGuildTokenRoute
  ApiSuspiciousGuildIdRoute: typeof ApiSuspiciousGuildIdRoute
  ApiVerifyTokenRoute: typeof ApiVerifyTokenRoute
  ApiVerifyPendingRoute: typeof ApiVerifyPendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/callback': {
      id: '/api/callback'
      path: '/api/callback'
      fullPath: '/api/callback'
      preLoaderRoute: typeof ApiCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-ip': {
      id: '/api/check-ip'
      path: '/api/check-ip'
      fullPath: '/api/check-ip'
      preLoaderRoute: typeof ApiCheckIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flag': {
      id: '/api/flag'
      path: '/api/flag'
      fullPath: '/api/flag'
      preLoaderRoute: typeof ApiFlagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit/$guildId': {
      id: '/api/audit/$guildId'
      path: '/api/audit/$guildId'
      fullPath: '/api/audit/$guildId'
      preLoaderRoute: typeof ApiAuditGuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord': {
      id: '/api/auth/discord'
      path: '/api/auth/discord'
      fullPath: '/api/auth/discord'
      preLoaderRoute: typeof ApiAuthDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guild/$guildId': {
      id: '/api/guild/$guildId'
      path: '/api/guild/$guildId'
      fullPath: '/api/guild/$guildId'
      preLoaderRoute: typeof ApiGuildGuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guild/register': {
      id: '/api/guild/register'
      path: '/api/guild/register'
      fullPath: '/api/guild/register'
      preLoaderRoute: typeof ApiGuildRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guild/token': {
      id: '/api/guild/token'
      path: '/api/guild/token'
      fullPath: '/api/guild/token'
      preLoaderRoute: typeof ApiGuildTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suspicious/$guildId': {
      id: '/api/suspicious/$guildId'
      path: '/api/suspicious/$guildId'
      fullPath: '/api/suspicious/$guildId'
      preLoaderRoute: typeof ApiSuspiciousGuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify/$token': {
      id: '/api/verify/$token'
      path: '/api/verify/$token'
      fullPath: '/api/verify/$token'
      preLoaderRoute: typeof ApiVerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify/pending': {
      id: '/api/verify/pending'
      path: '/api/verify/pending'
      fullPath: '/api/verify/pending'
      preLoaderRoute: typeof ApiVerifyPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VerifyRoute: VerifyRoute,
  ApiCallbackRoute: ApiCallbackRoute,
  ApiCheckIpRoute: ApiCheckIpRoute,
  ApiFlagRoute: ApiFlagRoute,
  ApiAuditGuildIdRoute: ApiAuditGuildIdRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthDiscordRoute: ApiAuthDiscordRoute,
  ApiGuildGuildIdRoute: ApiGuildGuildIdRoute,
  ApiGuildRegisterRoute: ApiGuildRegisterRoute,
  ApiGuildTokenRoute: ApiGuildTokenRoute,
  ApiSuspiciousGuildIdRoute: ApiSuspiciousGuildIdRoute,
  ApiVerifyTokenRoute: ApiVerifyTokenRoute,
  ApiVerifyPendingRoute: ApiVerifyPendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
